### ISSUE TITLE
Is there a way to interpolate the orbit from a navigation file?

### ISSUE THREAD

**Issue by jpmdodev** [GNSSpy-Project/gnsspy#1]
I would like to generate it from the Broadcast Ephemeris data instead of sp3. I don't know if it is possible. By the way ... Can I choose a local sp3 file?

`orbit = gp.sp3_interp(station.epoch, interval=station.interval, poly_degree=16, sp3_product="gfz", clock_product="gfz")`

**Comment by geomsi** [comment]
Hi João,

You can use your sp3 file (as long as the file format is not changed) by specifying its initials in the `gp.sp3_interp` function. Let's say you want to use the sp3 file from SIO products (`sp3_product="sio"`). The function will see that the sp3 file is locally available in the working directory and will not try to download from ftp server. 

As for the broadcast ephemeris data, currently we do not support the computation from navigation file, though we provide a function to read it. But we are going to add new features in the next release until the end of this April, and there will be a function for computation with Keplerian parameters.
